# path: .github/workflows/ci.yml
name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pytest pytest-asyncio pytest-cov coverage ruff black mypy fakeredis cryptography fastapi uvicorn pydantic pydantic-settings httpx
      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (black)
        run: black --check .
      - name: Type check (mypy)
        run: mypy || true
      - name: Tests + coverage
        run: pytest --cov --cov-report=xml --cov-report=term-missing
      - name: Coverage gate (≥85% changed)
        run: python .ci/coverage_gate.py
