# path: ci/github-actions.yml
name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system deps
        run: sudo apt-get update -y
      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install pytest pytest-asyncio coverage pytest-cov ruff black mypy
      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (black)
        run: black --check .
      - name: Type check (mypy)
        run: mypy || true
      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report=xml --cov-report=term-missing
      - name: Coverage gate ≥85% for changed modules
        run: |
          python .ci/coverage_gate.py
